monitor.libcamera.rules = [
  {
    matches = [
      {
        node.name = "~libcamera_input.*SB_.PC00.LNK1*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1000
      }
    }
  }
]
